[build]
  publish = "dist/my-angular-app/browser"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200
  publish = "dist/my-angular-app/browser"
